### ISSUE TITLE
Validar auto estacionado

### ISSUE THREAD

**Issue by Gambled23** [Gambled23/The-Parking-Zone#35]

**Comment by Gambled23** [comment]
Podemos hacer que el cajón se ponga en modo "espera" al general el boleto, en modo "ocupado" al estacionarse el auto, y desocupado cuando ya se va

Para detectar que el auto se estacionó, se leerá el ticket y el servomotor levantará la pluma para que el auto se pueda estacionar

**Comment by sami-sopas** [comment]
Hacer algo asi total https://youtu.be/9dyaI3GyUtc

**Comment by Gambled23** [comment]
> Hacer algo asi total https://youtu.be/9dyaI3GyUtc

El problema es q en la maqueta no vamos a tener placas XD

**Comment by sami-sopas** [comment]
Pues le hacemos unos carros y que tengan placa pa que su unica funcion sea esa, el pedo va ser la camara onde va estar Xd

**Comment by Gambled23** [comment]
Nomás la cámara de la laptop, pq ps no hay más XD

**Comment by Gambled23** [comment]
So, ninguna idea?

**Comment by sami-sopas** [comment]
Tengo entendido q cada sensor esta asignado a cierto cajon, asi q supongo que una vez se pida el boleto, guardar el lugar en donde se supone que deberia estacionarse ese carro, y en cuanto uno de los sensores sea activado (evento), verificar si el que se activo es correspondiente al cajon en el que deberia estar ese auto, si se activo algun otro sensor de otro cajon, se podria considerar que el auto se estaciono donde no deberia y ahi mandar una notificacion, pero como nose ni como funciona esto ahi lo dejo

**Comment by Gambled23** [comment]
El problema es q no funciona por evento, funciona cuando le das a un botón y no c cómo cambiar eso

**Comment by sami-sopas** [comment]
Y no se puede manejar como un proceso en segundo plano o algo asi?

**Comment by Gambled23** [comment]
Ps ahí ya tendría que ver Alex q él es el responsable de esa parte

**Comment by Gambled23** [comment]
Despues de testear con sensores concluí en que la mejor manera de hacerlo es ejecutando un lector de QR parecido al de salida cerca al de cada cajón, si el numero del ticket coincide con el numero del cajón, permitir el acceso, si no, negarlo

**Comment by Gambled23** [comment]
> Despues de testear con sensores concluí en que la mejor manera de hacerlo es ejecutando un lector de QR parecido al de salida cerca al de cada cajón, si el numero del ticket coincide con el numero del cajón, permitir el acceso, si no, negarlo

revisar #40
