### ISSUE TITLE
Poner restricción de caracteres (máximo 50) para el nombre de usuario/contraseña

### ISSUE THREAD

**Issue by cybness** [Gambled23/The-Parking-Zone#42]
Necesitamos que truene Cesarín ayuda

**Comment by Gambled23** [comment]
no le voy a meter bugs al programa nomás pa q lo hagan tronar, mucho me costó sacarselos xddd

**Comment by cybness** [comment]
No es exactamente pa que truene pues jkdad sería una restricción para prueba de defectos, pero si queda de más así está bien.
