### ISSUE TITLE
Un poqutio descuadrado en windows

### ISSUE THREAD

**Issue by sami-sopas** [Gambled23/The-Parking-Zone#55]
una ligerez vaya
![imagen_2023-05-21_160408070](https://github.com/Gambled23/The-Parking-Zone/assets/99571985/95416d8f-2f76-44f5-ad04-b5e275002f26)
![image](https://github.com/Gambled23/The-Parking-Zone/assets/99571985/6252ce9f-b93e-4e65-b6a3-263d51750954)

**Comment by Gambled23** [comment]
pon tu windows al 100% en vez del 125% jej
pq creo que eres al unico al que le está dando ese error, ha de ser por eso

**Comment by Gambled23** [comment]
BUENAS TARDES GRACIAS POR COMENTAR
